### ISSUE TITLE
Introduce helper method "isRHBQ()" to differentiate between upstream and RH build

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-framework#1215]
Introduce helper method "isRHBQ()" to differentiate between upstream and RH build

In https://github.com/quarkus-qe/quarkus-test-suite I noticed code like `QuarkusProperties.getVersion().contains("redhat")` occurring in several places.

We should have central helper method in FW.

**Comment by TimonCzech** [comment]
Can I take it?

**Comment by michalvavrik** [comment]
> Can I take it?

yep
