### ISSUE TITLE
Refactor detection rules of Build properties

### ISSUE THREAD

**Issue by Sgitario** [quarkus-qe/quarkus-test-framework#174]
At the moment, the build detection rules are defined in https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-core/src/main/resources/build-time-list.
However, this might change depending on the Quarkus version and may vary over time.
We can overwrite this file in a test suite, however, I think it makes more sense to have some more smart logic here to do what is being done in https://quarkus.io/guides/all-config.html

**Comment by michalvavrik** [comment]
I just hit issue https://github.com/quarkus-qe/quarkus-test-framework/pull/829 due to the fact we have this hardcoded. IMHO it can be as easy as building SmallRye config with correctly set config sources.

**Comment by michalvavrik** [comment]
Note for myself: when this get fixed, we need to revert changes made here https://github.com/quarkus-qe/quarkus-test-suite/pull/1317
