### ISSUE TITLE
Print what service / app is executed when `[app] Initialize service` is printed

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-framework#179]
Print what service / app is executed when `[app] Initialize service` is printed

I would at least appreciate information if the service is going to be executed in JVM / DEV / NATIVE mode

For docker based services I would like to see the image name if possible.

```
[app] Initialize service (Quarkus JVM mode)
[app] Initialize service (Quarkus DEV mode)
[app] Initialize service (Quarkus NATIVE mode)
[keycloak] Initialize service (jboss/keycloak:15.0.0)
etc.
```

**Comment by Sgitario** [comment]
This must be done in the `BaseService` and the service display name must be delegated to the managed resource (having a display name method to be extended) and used in the base service: `Log.info(app, "Initialize service (%s)", xx.displayName)`
