### ISSUE TITLE
Add KafkaContainer implementation with SSL and SASL enabled

### ISSUE THREAD

**Issue by Sgitario** [quarkus-qe/quarkus-test-framework#248]
The idea would be to extend the current implementation to allow to customize the kafka container as much as possible.

SSL Implementation can be found in https://github.com/quarkus-qe/quarkus-test-suite/blob/main/messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/ssl/SslStrimziKafkaTestResource.java.

**Comment by pjgg** [comment]
Kafka has a [server.properties file](https://github.com/apache/kafka/blob/trunk/config/server.properties) that allow you to configure your kafka instance. The main idea of this ticket is to be able to set up your own custom Kafka through the Quarkus test Framework. 

Main commits: 
SSL: https://github.com/quarkus-qe/quarkus-test-suite/blob/main/messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/ssl/SslStrimziKafkaTestResource.java

OverwriteServerProperties: https://github.com/quarkus-qe/quarkus-test-suite/pull/231/files#diff-c956cdac94b49262e2ba359c6d451993047a1f81eab4f82730dfa19fc8e34445R14

**Comment by mjurc** [comment]
There's also SASL config that should be considered for this feature.
