### ISSUE TITLE
Tests are executed before @DevModeQuarkusApplication is ready

### ISSUE THREAD

**Issue by mjurc** [quarkus-qe/quarkus-test-framework#249]
Sometimes, tests are ran before `@DevModeQuarkusApplication` is ready and listening.

A better readiness check needs to be added.

Example application:

https://github.com/quarkus-qe/quarkus-test-suite/pull/201/files#diff-8dbc1de5285b4921aca11433db28c6b2f3a40b4bf2192da988f50354d04c624eR15

**Comment by Sgitario** [comment]
> Sometimes, tests are ran before `@DevModeQuarkusApplication` is ready and listening.
> 
> A better readiness check needs to be added.

Can you attach/describe a reproducer please?

**Comment by mjurc** [comment]
Done!
