### ISSUE TITLE
BaseService cannot return hostname without protocol

### ISSUE THREAD

**Issue by fedinskiy** [quarkus-qe/quarkus-test-framework#263]
BaseService and its descendant classes, e.g. RestService, have method getHost, which returns string, which looks like "http://localhost". In most places our code either replaces "http" in this string with some other protocol(e.g. "jdbc") or glues it together with results of getPort method of the same class. Also, there are problems with API, which accepts only URLs or URIs, since we have to parse output of those methods.

I suggest to either:
a) Replace these two methods with method getURL (or getURI)
b) Change the method getHost, so it will return only a host.

**Comment by Sgitario** [comment]
+1 this area needs a lot of improvement. Feel free to refactor the solution or ideas.
