### ISSUE TITLE
OpenShiftDeploymentStrategy.UsingOpenShiftExtension doesn't copy all maven arguments

### ISSUE THREAD

**Issue by mmuzikar** [quarkus-qe/quarkus-test-framework#289]
When running a testsuite with additional maven arguments the openshift extension deployment strategy should use these arguments for the deployment. Currently it looks like some arguments get used, such as `quarkus.platform.version`, `quarkus.platform.artifact-id` and `quarkus.platform.group-id`. However when using properties such as `-Dversion.camel.quarkus=2.2.0` the argument is not used in the subsequent mvn builds.

Nor does `camel-quarkus-bom.version` from https://github.com/quarkus-qe/quarkus-test-suite/blob/main/pom.xml#L33 get used

**Comment by Sgitario** [comment]
Only the arguments starting with `quarkus.` are propagated.
