### ISSUE TITLE
CLI dev mode resources do not terminate

### ISSUE THREAD

**Issue by jsmrcka** [quarkus-qe/quarkus-test-framework#328]
Apps created with CLI (`QuarkusCliClient`) and ran in dev mode do not terminate properly and remain running, even after an explicit stop call.
```
    @Inject
    static QuarkusCliClient cliClient;

    @Test
    public void myTest() {
        // Create application
        QuarkusCliRestService app = cliClient.createApplication("app");

        // Build on Jvm
        QuarkusCliClient.Result result = app.buildOnJvm();
        assertTrue(result.isSuccessful(), "The application didn't build on JVM. Output: " + result.getOutput());

        // Start using DEV mode
        app.start();
        app.given().get().then().statusCode(HttpStatus.SC_OK);

        // Stop
        app.stop();
    }
```

#### Steps to reproduce:
In `quarkus-test-framework` root, run:
```
mvn clean verify -pl quarkus-test-cli/ -am -Prun-cli-tests,framework
```
The tests finish successully, but the apps' instances remain in memory and can be seen in list of processes. Also, there are errors in the test log:
```
[ERROR] Port 5005 in use, not starting in debug mode
```
which is a result of multiple resources started in dev mode and not terminated.

#### Affected version
`0.0.17-SNAPSHOT`

**Comment by pjgg** [comment]
To me looks that the process is terminated but there is something in the generated app target folder that makes quarkus-cli think that the app is still running. 

Workaround: Remove the generated app target folder before start&stop your app

```
private void removeTargetFolder(QuarkusCliRestService app) throws IOException {
        Runtime.getRuntime().exec("rm -rf " + app.getServiceFolder() + "/target");
    }
```

**Comment by rsvoboda** [comment]
Running processes trouble is resolved. It was fixed in https://github.com/quarkus-qe/quarkus-test-framework/pull/383

Removal of target folder is not related tho this issue, it's related to `shouldAddAndRemoveExtensions` test case when app gets restarted but not the right version of Quarkus gets picked, thus the removal of `target` is dirty help, bu the right workaround is to generate the app with the expected BOM version.
