### ISSUE TITLE
README doesn't show the added value of the framework

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-framework#331]
README doesn't show the added value of the framework

Main features section
 - Different target environments are not highlighted enough
 - Support for both JVM and Native mode should be highlighted tess
 - Test services are not mentioned
 
Getting Started section
 - ATM showing just what Quarkus can handle on it's own
 - Nothing from added features - e.g. native out of the box, OpenShift, Kubernetes
   - https://github.com/quarkus-qe/quarkus-test-framework/blob/main/examples/blocking-reactive-model/src/test/java/io/quarkus/qe/KubernetesGreetingResourceIT.java
   - https://github.com/quarkus-qe/quarkus-test-framework/blob/main/examples/blocking-reactive-model/src/test/java/io/quarkus/qe/OpenShiftGreetingResourceIT.java
 - No mention of examples directory
 - Consider to link tests from https://github.com/quarkus-qe/quarkus-test-framework/tree/main/examples/greetings/src/test/java/io/quarkus/qe as a nice starting point to see many options this framework provides

**Comment by fedinskiy** [comment]
As of May of 2023, all the information is contained in the wiki:

Main features section

-     Different target environments has a separate table with support of feature: (https://github.com/quarkus-qe/quarkus-test-framework/wiki)
-     Support for both JVM and Native mode is highlighted in the same table
-     Test services has their own section(https://github.com/quarkus-qe/quarkus-test-framework/wiki/4.-Services)

Getting Started section
-     Shows additional features (eg https://github.com/quarkus-qe/quarkus-test-framework/wiki/1.-Getting-Started#buildruntime-properties)
- Shows added features - e.g. native out of the box, OpenShift, Kubernetes (https://github.com/quarkus-qe/quarkus-test-framework/wiki/1.-Getting-Started#openshift-jvm-native-dev-mode-and-more)
-   Mentions examples directory (https://github.com/quarkus-qe/quarkus-test-framework/wiki/1.-Getting-Started#multiple-quarkus-applications) and links tests from there (https://github.com/quarkus-qe/quarkus-test-framework/wiki/1.-Getting-Started#openshift-jvm-native-dev-mode-and-more)


@rsvoboda is there anything you would like to add?

**Comment by rsvoboda** [comment]
Let's conclude this then.
