### ISSUE TITLE
Avoid using personal account images

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-framework#332]
One example: `quay.io/pjgg/db2:11.5.5.0`

Such images shouldn't be used, `quarkusqeteam` organisation should be used instead
e.g. https://quay.io/repository/quarkusqeteam/db2?tab=tags

**Comment by mjurc** [comment]
I didn't find this in the framework, but it certainly is in test suite:

https://github.com/quarkus-qe/quarkus-test-suite/blob/main/sql-db/vertx-sql/src/test/resources/docker-compose.yaml

Issue: https://github.com/quarkus-qe/quarkus-test-suite/issues/390

Closing this as I didn't find any other occurence.
