### ISSUE TITLE
Debug mode flag

### ISSUE THREAD

**Issue by pjgg** [quarkus-qe/quarkus-test-framework#345]
Based on [this ticket](https://github.com/quarkus-qe/quarkus-test-framework/pull/344) and in a Zulip conversation looks that we should create a `-Ddebug` flag that keeps running all containers after test execution. This feature helps developers to understand and debug their scenarios. 

**k8s/Openshift**
- I k8s/openshift is almost done by [this ticket](https://github.com/quarkus-qe/quarkus-test-framework/pull/344). It's only needed to create a `-Ddebug` flag in order to trigger the current behavior:

```
ts.kubernetes.delete.project.after.all=false
ts.kubernetes.ephemeral.namespaces.enabled=false
```
**Baremetal**

Requirements: If `-Ddebug` is provided then containers and applications should keep running after test execution

**Comment by michalvavrik** [comment]
I'll change priority as (way I plan to impl. it, not just K8) it basically fixes https://github.com/quarkus-qe/quarkus-test-suite/issues/145 which has high priority. 

cc @mjurc
