### ISSUE TITLE
Runs on OpenShift fail on ping-pong test

### ISSUE THREAD

**Issue by fedinskiy** [quarkus-qe/quarkus-test-framework#352]
This is happening since, at least, late November, but probably from early October.
Log example:
https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk11-openshift-tf-jvm-githubci/108/consoleFull

`SEVERE Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.ClassExtensionContext@14823f76: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message`

**Comment by rsvoboda** [comment]
@mjurc says it can be connected to OpenShift Serverless 1.19 / OpenShift 4.9
