### ISSUE TITLE
Establish a branching and release strategy

### ISSUE THREAD

**Issue by mjurc** [quarkus-qe/quarkus-test-framework#375]
With Jandex breaking binary compatibility with later releases of Quarkus after 2.2, I propose staring a branching strategy as follows:

* `quarkus-qe/quarkus-test-framework/main`, based on latest released quarkus, used in `quarkus-qe/quarkus-test-suite/main`, release stream `1.x`
* `quarkus-qe/quarkus-test-framework/1.0`, based on latest released quarkus 2.2, used in `quarkus-qe/quarkus-test-suite/2.2`, release stream `1.0.z`

**Comment by pjgg** [comment]
The release strategy is already implemented and documented

DocRef: https://github.com/quarkus-qe/quarkus-test-framework/blob/main/RELEASE.md
