### ISSUE TITLE
Support `command` statements in Openshift scenarios 

### ISSUE THREAD

**Issue by pjgg** [quarkus-qe/quarkus-test-framework#427]
I had an issue with a Mysql scenario + Redhat container image: `registry.access.redhat.com/rhscl/mysql-80-rhel7`
The issue is something like this:

```
Packet for query is too large (12884616 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.; nested exception is com.mysql.jdbc.PacketTooBigException: Packet for query is too large (12884616 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.
```

The solution should be something as simple as increasing the property `max_allowed_packet` to the right value

```
 @Container(image = "${mysql.80.image}", port = MYSQL_PORT, expectedLog = "Only MySQL server logs after this point", command = " --max-allowed-packet=5526600")
    static MySqlService base = new MySqlService().withDatabase("base");
```

However currently, we are not supporting `command` statement in Openshift scenarios. 
Take a look to the Openshift template: https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-openshift/src/main/resources/openshift-deployment-template.yml#L31

I will expect something like: 
```
 - name: command-demo-container
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
```

Note: on containers scenarios is already implemented.

**Comment by michalvavrik** [comment]
Implemented by https://github.com/quarkus-qe/quarkus-test-framework/pull/498

**Comment by michalvavrik** [comment]
Ah, but that's not fault of impl., there is better way to set max allowed packet anyway.
