### ISSUE TITLE
`GitRepositoryQuarkusApplication` doesn't resolve internal artifacts

### ISSUE THREAD

**Issue by pjgg** [quarkus-qe/quarkus-test-framework#432]
If you are pointing to a monorepo that depends on other internal artifacts that must be released as a previous project compilation stage, then annotation `GitRepositoryQuarkusApplication`  doesn't resolve those dependencies. 

Example:
```
@GitRepositoryQuarkusApplication(repo = "https://github.com/quarkusio/quarkus-workshops.git", contextDir = "quarkus-workshop-super-heroes/super-heroes/rest-villains", branch = "3d3425a15daacf1c774cb7f5bc24228c4a623256", mavenArgs = "-Dquarkus.package.type=uber-jar -DskipTests -Dquarkus.platform.group-id=${QUARKUS_PLATFORM_GROUP-ID} -Dquarkus.platform.version=${QUARKUS_VERSION}")
    static final RestService app = new RestService()
```

This project `quarkus-workshop-super-heroes/super-heroes/rest-villains` depends on `extension-version` that is an internal artifact:

rest-villains pom: https://github.com/quarkusio/quarkus-workshops/blob/main/quarkus-workshop-super-heroes/super-heroes/rest-villains/pom.xml#L98

extension-version pom: https://github.com/quarkusio/quarkus-workshops/blob/main/quarkus-workshop-super-heroes/super-heroes/extension-version/pom.xml

Would be great to be able to execute some previous steps to compilation time, or at least to be able to compile the whole project even if later you are going to deploy a single module.

**Comment by rsvoboda** [comment]
Closing. This is staled for the last two and a half years, OpenShiftWorkshopVillainsIT was removed from the TS.
