### ISSUE TITLE
Containers, started by devmode, are not stopped automatically

### ISSUE THREAD

**Issue by fedinskiy** [quarkus-qe/quarkus-test-framework#602]
Applications, started with `@DevModeQuarkusApplication` may spin up containers. Unfortunately, this containers are not removed, not even stopped after the end of the test. Usually this is done by ryuk, but if we disable it(e.g.this is sometimes required when working with podman, without workarounds from[2]), they are kept in running state.
Aside from consuming excessive resources, this also lead to failures in tests, since dev-mode can reuse running containers, and some of tests[1] expect that containers would be started specifically for the test.

How to reproduce this behavior:

1) `examples/database-mysql/`
2) `export TESTCONTAINERS_RYUK_DISABLED=true`
3) mvn clean verify -Dit.test=DevModeMySqlDevServicesDatabaseIT
4) `docker ps` — Results are not empty

If we run `quarkus:dev` inside the folder and stop it with "Ctrl+C", the docker task is removed as well, so I presume it is not a bug in upstream.

[1] https://github.com/quarkus-qe/quarkus-test-suite/blob/main/security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/DevModeOidcSecurityIT.java#L23
[2] https://quarkus.io/guides/podman#testcontainers-privileges

**Comment by fedinskiy** [comment]
Workaround: add `DockerUtils.stopContainersByImage` in pre-start phase of affected applications, eg `.onPreStart(ignored -> DockerUtils.stopContainersByImage("quay.io/keycloak/keycloak:19.0.0"))`

**Comment by mjurc** [comment]
@fedinskiy this issue occurs only when Ryuk is disabled for podman, right?

Do we still need to disable Ryuk? Quarkus guide has a different fix - see https://quarkus.io/guides/podman#testcontainers-privileges

Can you update this issue with findings from this?

**Comment by fedinskiy** [comment]
@mjurc this issue occurs when Ryuk is disabled. Ryuk may be disabled for podman(now fixed) or due to other reasons (eg if we decide to stop using testcontainers).
I would say, this is not a pressing concern, but something we would like to fix eventually(FW generally closes used resources by itself, I do not know, why it doesn't do it in this case).

**Comment by michalvavrik** [comment]
I'll check in week 19/2023.

**Comment by michalvavrik** [comment]
This happens because the process that closes MySQL TestContainer is killed forcibly, while with CTRL+C (as long as you press it once) or with when you press `q`, the process is normally terminated
