### ISSUE TITLE
JaegerContainer - useOtlpCollector default change proposal

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-framework#653]
Currently `JaegerContainer` interface defaults `useOtlpCollector` to `false`.
https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-service-jaeger/src/main/java/io/quarkus/test/services/JaegerContainer.java#L32

Upstream moves away from direct rest point usage - OpenTelemetry Jaeger exporter moved to Quarkiverse in 2.14, OpenTracing is marked as deprecated, and the path forward is using OTLP.

I propose to change the `useOtlpCollector` default to `true`.  It should make the experience with our framework a bit better.

I've hit the trouble when enhancing OpenTelemetry coverage and it took some time to realize that I need to have `@JaegerContainer(useOtlpCollector = true)`

@mjurc @pjgg fyi

**Comment by mjurc** [comment]
This should be implemented on main.
