### ISSUE TITLE
Configuration: Allow to setup default factor timeouts

### ISSUE THREAD

**Issue by Sgitario** [quarkus-qe/quarkus-test-framework#75]
Allow configuring timeouts for services. For example, in order to configure startup service timeout, we could use:

```
ts.<SERVICE_NAME>.timeout.startup=10 # 10 minutes
```

The default for startup is 5 minutes. 

Moreover, let's allow to have some factor times to adapt our test suite to slower environments:

```
ts.global.timeout.factor=2.5 # Default 1.
```

This value will be used to multiply the timeouts (timeout x factor = total timeout). Example: if we define a timeout of 5 minutes with a factor of 2.5, the total timeout will be 5 x 2.5 = 12.5 minutes.

The factor should be suitable to be supplied from system properties.

At the moment, let's support only the startup timeout.

**Comment by rsvoboda** [comment]
`ts.<SERVICE_NAME>.timeout.startup=10m` looks more natural and there could be variant for seconds, e.g. `30s`

**Comment by Sgitario** [comment]
> `ts.<SERVICE_NAME>.timeout.startup=10m` looks more natural and there could be variant for seconds, e.g. `30s`

Do you mean that you prefer to deal with timeouts without another `factor` property? Or just that you prefer to define timeout using duration annotation?

**Comment by rsvoboda** [comment]
`ts.<SERVICE_NAME>.timeout.startup=10` = > `ts.<SERVICE_NAME>.timeout.startup=10m`

to make it self describing what unit is used
