### ISSUE TITLE
Allow to configure URL to check for running service

### ISSUE THREAD

**Issue by leonvoe** [quarkus-qe/quarkus-test-framework#836]
When I am running an `@OpenShiftScenario` test, the services get deployed as expected. But after the test framework has started the deployment & pods, there is an ongoing check executed which checks for whether the service is running (the route is reachable) or not. In my case, I would need to configure the URL which is used (the route which is pinged), because the default route used here is private on my OpenShift Cluster. 
The method which leads to the problems is `routeIsReachable` in the  `OpenShiftQuarkusApplicationManagedResource` class.
Is there any opportunity, to configure the URL used by the check here?

Thanks for looking into this,
Best regards

**Comment by michalvavrik** [comment]
hey @leonvoe , sorry, I didn't mention this issue. I'll try to have a look when there is a little time.
