### ISSUE TITLE
S2I: ARTIFACT_COPY_ARGS is wrong for Quarkus 1.13+

### ISSUE THREAD

**Issue by mjurc** [quarkus-qe/quarkus-test-framework#85]
Update the property at https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-openshift/src/main/resources/quarkus-s2i-source-build-template.yml#L35 to match the path of `target/quarkus-app/quarkus-run.jar` in the builder container.

**Comment by Sgitario** [comment]
The default version will not modify the ARTIFACT_COPY_ARGS, so users would need to provide a custom template to amend this configuration. See examples/external-applications and the test OpenShiftS2iQuickstartForVersion1xIT.
